"""Provenance signals from Zhao et al., "Data Provenance for Image Auto-Regressive Generation".

Stage 1 uses the tokenizers' original encoders as the decoder inverse D^-1 (no fine-tuning).
All pixel-space losses are MSE on [0,1] images so the two families are on the same scale.
  quant     QuantLoss (Eq. 5): ||f - Q^-1(Q(f))||^2 in latent space
  enc1      EncLoss (Eq. 9): ||Rec(x) - x||^2, Rec(x) = D(Q^-1(Q(E(x))))
  enc2      ||Rec(Rec(x)) - Rec(x)||^2, the complexity estimate
  cal       calibrated EncLoss (Eq. 10) = enc1 / enc2
  comb      combined signal (Eq. 11) = quant * cal
  tok_match fraction of tokens unchanged between x and Rec(x) (extra, not in the paper)

Every function takes a batch x: [B,3,256,256] in [0,1] and returns a dict of [B] tensors, one value per image.
Lower losses (and higher tok_match) mean the image is more likely generated by that family.
||.||^2 is implemented as a per-image mean over elements (MSE), not a sum.
"""
import torch
import torch.nn.functional as F


def _mse(a, b):
    """Per-sample mean squared error: [B,...] x [B,...] -> [B]."""
    return (a - b).pow(2).flatten(1).mean(1)


@torch.no_grad()
def rar_signals(tok, x):
    """x: [B,3,256,256] in [0,1]. tok: RAR MaskGIT-VQGAN PretrainedTokenizer.

    Returns quant, quant_p90, enc1, enc2, cal, comb, tok_match, each of shape [B].
    """
    def encode(img):
        # features f, quantized features f_Z = Q^-1(Q(f)), and token indices Q(f)
        f = tok.encoder(img)
        zq, idx, _ = tok.quantize(f)
        return f, zq, idx

    def decode(zq):
        return tok.decoder(zq).clamp(0, 1)

    f, zq, idx = encode(x)
    rec1 = decode(zq)  # Rec(x)
    _, zq1, idx1 = encode(rec1)  # re-encode the reconstruction
    rec2 = decode(zq1)  # Rec(Rec(x))

    per_tok = (f - zq).pow(2).mean(1).flatten(1)  # [B, h*w]: quantization error per token position
    quant = per_tok.mean(1)  # QuantLoss (Eq. 5)
    enc1, enc2 = _mse(rec1, x), _mse(rec2, rec1)  # EncLoss (Eq. 9) and the complexity estimate
    cal = enc1 / enc2  # calibrated EncLoss (Eq. 10)
    return {
        "quant": quant,
        "quant_p90": per_tok.quantile(0.9, dim=1),
        "enc1": enc1, "enc2": enc2, "cal": cal, "comb": quant * cal,  # comb: Eq. 11
        "tok_match": (idx == idx1).float().mean(1),
    }


def _var_idx_to_fhat(quant, idx_list):
    """Multi-scale token indices -> quantized feature map f_hat [B,C,16,16].

    idx_list holds one [B, pn*pn] index tensor per scale (pn in quant.v_patch_nums). Each scale is looked up
    in the codebook, upsampled to 16x16 and passed through its quant_resi conv, and the results are summed.
    """
    B, C = idx_list[0].shape[0], quant.Cvae
    ms_h = [quant.embedding(idx).transpose(1, 2).reshape(B, C, pn, pn)
            for idx, pn in zip(idx_list, quant.v_patch_nums)]
    return quant.embed_to_fhat(ms_h, all_to_max_scale=True, last_one=True)


def var_token_search(quant, f, init_idx, n_iters=1200, lr=0.1, init_logit=10.0, eval_every=25):
    """Algorithm 3: gradient search over soft multi-scale token maps so their sum best matches f.

    Logits start at `init_logit` on the greedy tokens (paper: init with original quantization) and 0 elsewhere.
    The argmax of the soft optimum can be worse than the greedy start, so every `eval_every` iterations the
    hard tokens are scored and the best per sample is kept (never worse than greedy).
    Returns the hard tokens per scale.

    quant: VAR VectorQuantizer2. f: target features [B,C,16,16]. init_idx: greedy tokens per scale ([B, pn*pn]).
    n_iters / lr: Adam steps and learning rate on the logits.
    """
    emb = quant.embedding.weight.detach()  # [V, C]
    B, C, H, W = f.shape
    SN, V = len(quant.v_patch_nums), emb.shape[0]  # number of scales, codebook size
    f = f.detach()
    best_idx = [i.clone() for i in init_idx]
    best_loss = _mse(_var_idx_to_fhat(quant, best_idx), f)

    def keep_best(logits):
        """Score the argmax tokens and keep them for the samples where they beat the best so far."""
        idx = [l.detach().argmax(-1) for l in logits]
        loss = _mse(_var_idx_to_fhat(quant, idx), f)
        better = loss < best_loss
        best_loss[better] = loss[better]
        for b, i in zip(best_idx, idx):
            b[better] = i[better]

    with torch.enable_grad():  # the caller may run under no_grad; the search needs gradients
        # One [B, pn*pn, V] logit tensor per scale, peaked on the greedy token.
        logits = []
        for idx in init_idx:
            l = torch.zeros(B, idx.shape[1], V, device=f.device)
            l.scatter_(2, idx.unsqueeze(-1), init_logit)
            logits.append(l.requires_grad_(True))
        opt = torch.optim.Adam(logits, lr=lr)
        for it in range(n_iters):
            # Soft version of _var_idx_to_fhat: softmax-weighted codebook mix instead of a hard lookup.
            f_hat = torch.zeros_like(f)
            for si, (l, pn) in enumerate(zip(logits, quant.v_patch_nums)):
                z = (l.softmax(-1) @ emb).transpose(1, 2).reshape(B, C, pn, pn)
                if si < SN - 1:
                    z = F.interpolate(z, size=(H, W), mode="bicubic")
                f_hat = f_hat + quant.quant_resi[si / (SN - 1)](z)
            # per-sample mean, summed so each sample's gradient is independent of batch size
            loss = (f_hat - f).pow(2).flatten(1).mean(1).sum()
            opt.zero_grad(set_to_none=True)
            loss.backward()
            opt.step()
            if (it + 1) % eval_every == 0 or it == n_iters - 1:
                with torch.no_grad():
                    keep_best(logits)
    return best_idx


@torch.no_grad()
def var_signals(vae, x, n_iters=1200, lr=0.1, init_logit=10.0):
    """x: [B,3,256,256] in [0,1]. vae: VAR multi-scale VQVAE (expects [-1,1]).

    quant_greedy uses VAR's own scale-wise greedy quantization (Algorithm 2);
    quant uses the optimized token search (Algorithm 3) when n_iters > 0, else equals quant_greedy.
    EncLoss reconstructions use the greedy quantization.
    n_iters, lr, init_logit are passed to var_token_search.

    Returns quant_greedy, quant, enc1, enc2, cal, comb_greedy, comb, tok_match, each of shape [B].
    """
    q = vae.quantize

    def encode(img01):
        # [0,1] image -> continuous features f (VAR's encoder expects [-1,1])
        return vae.quant_conv(vae.encoder(img01 * 2 - 1))

    def decode(f_hat):
        # quantized features -> [0,1] image
        return (vae.fhat_to_img(f_hat) + 1) / 2

    f = encode(x)
    idx = q.f_to_idxBl_or_fhat(f, to_fhat=False)  # greedy multi-scale tokens (Algorithm 2)
    f_hat = _var_idx_to_fhat(q, idx)
    rec1 = decode(f_hat)  # Rec(x)
    f1 = encode(rec1)  # re-encode the reconstruction
    idx1 = q.f_to_idxBl_or_fhat(f1, to_fhat=False)
    rec2 = decode(_var_idx_to_fhat(q, idx1))  # Rec(Rec(x))

    quant_greedy = _mse(f_hat, f)  # QuantLoss (Eq. 5) with greedy tokens
    if n_iters > 0:
        idx_opt = var_token_search(q, f, idx, n_iters=n_iters, lr=lr, init_logit=init_logit)
        quant = _mse(_var_idx_to_fhat(q, idx_opt), f)
    else:
        quant = quant_greedy
    enc1, enc2 = _mse(rec1, x), _mse(rec2, rec1)  # EncLoss (Eq. 9) and the complexity estimate
    cal = enc1 / enc2  # calibrated EncLoss (Eq. 10)
    return {
        "quant_greedy": quant_greedy, "quant": quant,
        "enc1": enc1, "enc2": enc2, "cal": cal,
        "comb_greedy": quant_greedy * cal, "comb": quant * cal,  # Eq. 11
        # all 680 tokens across the 10 scales, compared position by position
        "tok_match": (torch.cat(idx, 1) == torch.cat(idx1, 1)).float().mean(1),
    }
