"""Stage 1 decision rule: nearest family + per-family threshold, all fit on train only (no outliers needed).

1. Each family f has one provenance score s_f (lower = more likely generated by f). It is standardised as
   z_f = (log s_f - mean) / std using train images of family f.
2. Family = argmin_f z_f. If that z exceeds tau_f, the q-quantile of z_f over the family's own train images,
   the image is an outlier (it is not typical of any known family).
3. Size within the predicted family: a logistic regression on all signals, trained on that family's train images.

Usage:
    model = NearestFamilyThreshold({"rar": "rar_cal", "var": "var_cal"}, q=0.95, size_cols=feature_cols).fit(train)
    labels = model.predict(df)  # one of the 9 label strings per row
"""
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

KNOWN_FAMILIES = ["rar", "var"]


def log_features(df: pd.DataFrame, cols) -> np.ndarray:
    """Losses are positive and right-skewed, so log them; fractions (tok_match) stay as they are."""
    return np.column_stack([df[c].values if c.endswith("tok_match") else np.log(df[c].values) for c in cols])


class NearestFamilyThreshold:
    """Nearest-family classifier with a per-family outlier threshold and an optional size classifier.

    score_cols: family -> loss column (lower = more likely that family), one per family in KNOWN_FAMILIES.
    q: quantile of the family's own train z-scores used as the outlier threshold tau.
    size_cols: feature columns for the per-family size classifier; None always predicts the smallest model.
    C: inverse regularisation strength of the size LogisticRegression.

    Fitted attributes, keyed by family: mu_, sd_ (mean / population std of the log score), tau_, size_clf_.
    Input frames need the score / size columns, plus `family` and `label` for fit.
    """

    def __init__(self, score_cols: dict, q: float = 0.95, size_cols=None, C: float = 1.0):
        self.score_cols = score_cols  # family -> column name, e.g. {"rar": "rar_cal", "var": "var_cal"}
        self.q = q
        self.size_cols = size_cols
        self.C = C

    def fit(self, train: pd.DataFrame):
        """Fit mu_, sd_, tau_ (and size_clf_ if size_cols) per family on train. Train must have no outliers."""
        assert set(train.family) <= set(KNOWN_FAMILIES), "train must contain only known families"
        self.mu_, self.sd_, self.tau_, self.size_clf_ = {}, {}, {}, {}
        for fam in KNOWN_FAMILIES:
            own = train[train.family == fam]
            s = np.log(own[self.score_cols[fam]].values)
            self.mu_[fam], self.sd_[fam] = s.mean(), s.std()
            # outlier threshold: q-quantile of the family's own train z-scores
            self.tau_[fam] = np.quantile((s - self.mu_[fam]) / self.sd_[fam], self.q)
            if self.size_cols:
                # size classifier over the family's 4 labels
                clf = make_pipeline(StandardScaler(), LogisticRegression(C=self.C, max_iter=5000))
                self.size_clf_[fam] = clf.fit(log_features(own, self.size_cols), own.label.values)
        return self

    def family_z(self, df: pd.DataFrame) -> pd.DataFrame:
        """Columns z_rar, z_var: z_f = (log s_f - mu_f) / sd_f for every row (lower = more typical of f)."""
        return pd.DataFrame({f"z_{fam}": (np.log(df[self.score_cols[fam]].values) - self.mu_[fam]) / self.sd_[fam]
                             for fam in KNOWN_FAMILIES}, index=df.index)

    def predict_family(self, df: pd.DataFrame) -> pd.Series:
        """Per row: "rar", "var" or "outlier". The family with the lower z (ties -> rar), or outlier if z > tau."""
        z = self.family_z(df)
        fam = pd.Series(np.where(z.z_rar <= z.z_var, "rar", "var"), index=df.index)
        zmin = z.min(axis=1)  # z of the nearest family
        tau = fam.map(self.tau_)  # threshold of the nearest family
        return fam.where(zmin <= tau, "outlier")

    def predict(self, df: pd.DataFrame) -> pd.Series:
        """Full label per row (one of LABELS): predict_family, then the size within each known family."""
        fam = self.predict_family(df)
        pred = fam.copy()  # outliers keep the label "outlier"
        for f in KNOWN_FAMILIES:
            m = fam == f
            if m.any():
                if self.size_cols:
                    pred[m] = self.size_clf_[f].predict(log_features(df[m], self.size_cols))
                else:
                    pred[m] = {"rar": "rarb", "var": "var16"}[f]  # fixed-size baseline
        return pred
